# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('titre', models.CharField(max_length=320)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('contenu', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
            ],
        ),
    ]
