# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon'),
        ),
    ]
