# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 14:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161122_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='contenu',
            field=tinymce_4.fields.TinyMCEModelField(verbose_name='Contenu'),
        ),
    ]
