# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_website_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.URLField()),
                ('link_text', models.CharField(max_length=256)),
                ('icone', models.CharField(choices=[('Réseaux sociaux', (('fb.jpg', 'Facebook'), ('twitter.jpg', 'Twitter'), ('linkedin.jpg', 'Linkedin'))), ('Autres', (('fb.jpg', 'Facebook'),))], default='fb.jpg', max_length=128)),
            ],
        ),
    ]
