# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20161122_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('css_class', models.CharField(max_length=256, verbose_name='CSS classes')),
                ('css_id', models.CharField(max_length=128, verbose_name='CDD unique id')),
                ('css_inline', models.CharField(max_length=1200, verbose_name='CSS en ligne')),
                ('titre', models.CharField(max_length=512)),
                ('format', models.CharField(choices=[('FULL', 'Full width'), ('HALF', 'Half width'), ('THIRD', 'One third'), ('FOURTH', 'One fourth'), ('2FOURTH', 'Two fourth'), ('3FOURTH', 'Three fourth'), ('FIFTH', 'Large')], max_length=32, verbose_name='Format du bloc')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_author', to=settings.AUTH_USER_MODEL)),
                ('blocks', models.ManyToManyField(to='core.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_author', to=settings.AUTH_USER_MODEL)),
                ('blocks', models.ManyToManyField(to='core.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('css_class', models.CharField(max_length=256, verbose_name='CSS classes')),
                ('css_id', models.CharField(max_length=128, verbose_name='CDD unique id')),
                ('css_inline', models.CharField(max_length=1200, verbose_name='CSS en ligne')),
                ('titre', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('css_class', models.CharField(max_length=256, verbose_name='CSS classes')),
                ('css_id', models.CharField(max_length=128, verbose_name='CDD unique id')),
                ('css_inline', models.CharField(max_length=1200, verbose_name='CSS en ligne')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_author', to=settings.AUTH_USER_MODEL)),
                ('blocks', models.ManyToManyField(to='core.Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_author', to=settings.AUTH_USER_MODEL)),
                ('pages', models.ManyToManyField(related_name='website', to='core.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(to='core.Section'),
        ),
    ]
