# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_external_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='external_link',
            new_name='ExternalLink',
        ),
    ]
