# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161128_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='format',
            field=models.CharField(choices=[('FULL', 'Full width'), ('HALF', 'Half width'), ('THIRD', 'One third'), ('FOURTH', 'One fourth'), ('2FOURTH', 'Two fourth'), ('3FOURTH', 'Three fourth'), ('FIFT5', 'Large')], max_length=32, verbose_name='Format du bloc'),
        ),
    ]
