# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20161128_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aside_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='block',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='titre',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='website',
            name='pages',
        ),
        migrations.AddField(
            model_name='footer',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='core.Website'),
        ),
        migrations.AddField(
            model_name='header',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', to='core.Website'),
        ),
        migrations.AddField(
            model_name='page',
            name='websites',
            field=models.ManyToManyField(related_name='pages', to='core.Website'),
        ),
        migrations.AddField(
            model_name='section',
            name='nom',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='section',
            name='pages',
            field=models.ManyToManyField(related_name='sections', to='core.Page'),
        ),
        migrations.AlterField(
            model_name='block',
            name='format',
            field=models.CharField(choices=[('FULL', 'Full width'), ('HALF', 'Half width'), ('THIRD', 'One third'), ('FOURTH', 'One fourth'), ('2FOURTH', 'Two fourth'), ('3FOURTH', 'Three fourth'), ('FIFTH', 'One fifth')], max_length=32, verbose_name='Format du bloc'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='blocks',
            field=models.ManyToManyField(related_name='footer', to='core.Block'),
        ),
        migrations.AlterField(
            model_name='header',
            name='blocks',
            field=models.ManyToManyField(related_name='header', to='core.Block'),
        ),
        migrations.AlterField(
            model_name='section',
            name='blocks',
            field=models.ManyToManyField(related_name='section', to='core.Block'),
        ),
        migrations.AddField(
            model_name='aside',
            name='blocks',
            field=models.ManyToManyField(related_name='aside', to='core.Block'),
        ),
        migrations.AddField(
            model_name='aside',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aside', to='core.Website'),
        ),
    ]
