# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170104_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='external_links',
            field=models.ManyToManyField(related_name='website', to='core.ExternalLink'),
        ),
    ]
