# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_website_external_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='icone',
            field=models.CharField(choices=[('Réseaux sociaux', (('fb.jpg', 'Facebook'), ('twitter.jpg', 'Twitter'), ('linkedin.jpg', 'Linkedin'))), ('Autres', (('mail.jpg', 'Mail'),))], default='fb.jpg', max_length=128),
        ),
    ]
