# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_auto_20170112_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='external_links',
        ),
        migrations.AddField(
            model_name='externallink',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externallink',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
