# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161201_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='test',
        ),
    ]
