# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170112_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css_displayAside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='css_displayFooter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='css_displayHeader',
            field=models.BooleanField(default=True),
        ),
    ]
