# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 10:18
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170117_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='classe_titre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Classe1', 'Classe 1'), ('Classe2', 'Classe 2'), ('Classe3', 'Classe 3')], max_length=64, null=True, verbose_name='Type de titre'),
        ),
    ]
