# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('image_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.block',),
        ),
        migrations.CreateModel(
            name='BlockTexte',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Block')),
                ('texte', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.block',),
        ),
    ]
